[build]
  publish = "build"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/home"
  to = "/"
  status = 301

[[redirects]]
  from = "/skills"
  to = "/"
  status = 301

[[redirects]]
  from = "/experience"
  to = "/"
  status = 301

[[redirects]]
  from = "/projects"
  to = "/"
  status = 301

[[redirects]]
  from = "/education"
  to = "/"
  status = 301

[[redirects]]
  from = "/hobbies"
  to = "/"
  status = 301

[[redirects]]
  from = "/contact"
  to = "/"
  status = 301
